#logging.level:
logging:
  level:
    # The default log level is INFO,
    # so TRACE and DEBUG messages are not shown.
    # THESE SETTINGS HAVE NO EFFECT!
    #root: ERROR
    com.example.demo: TRACE
    #com.example.demo.dog: TRACE

server.port: 1919

spring:
  application:
    name: demo

  devtools:
    #add-properties: false
    restart:
      enabled: true