logging.level:
  root: error
  com.example.demo: trace
  com.example.demo.dog: trace

server.port: 1919

spring:
  application:
    name: demo

  devtools.restart:
    enabled: true
    # additional-paths: src/main/**